//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-javafx-widget\SWTAndroidXRecyclerView\src\main\java\androidx\recyclerview\widget\ScrollbarHelper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ScrollbarHelper")
#ifdef RESTRICT_ScrollbarHelper
#define INCLUDE_ALL_ScrollbarHelper 0
#else
#define INCLUDE_ALL_ScrollbarHelper 1
#endif
#undef RESTRICT_ScrollbarHelper

#if !defined (ADXScrollbarHelper_) && (INCLUDE_ALL_ScrollbarHelper || defined(INCLUDE_ADXScrollbarHelper))
#define ADXScrollbarHelper_

@class ADView;
@class ADXOrientationHelper;
@class ADXRecyclerView_LayoutManager;
@class ADXRecyclerView_State;

/*!
 @brief A helper class to do scroll offset calculations.
 */
@interface ADXScrollbarHelper : NSObject

#pragma mark Package-Private

/*!
 @param startChild View closest to start of the list. (top or left)
 @param endChild View closest to end of the list (bottom or right)
 */
+ (jint)computeScrollExtentWithADXRecyclerView_State:(ADXRecyclerView_State *)state
                            withADXOrientationHelper:(ADXOrientationHelper *)orientation
                                          withADView:(ADView *)startChild
                                          withADView:(ADView *)endChild
                   withADXRecyclerView_LayoutManager:(ADXRecyclerView_LayoutManager *)lm
                                         withBoolean:(jboolean)smoothScrollbarEnabled;

/*!
 @param startChild View closest to start of the list. (top or left)
 @param endChild View closest to end of the list (bottom or right)
 */
+ (jint)computeScrollOffsetWithADXRecyclerView_State:(ADXRecyclerView_State *)state
                            withADXOrientationHelper:(ADXOrientationHelper *)orientation
                                          withADView:(ADView *)startChild
                                          withADView:(ADView *)endChild
                   withADXRecyclerView_LayoutManager:(ADXRecyclerView_LayoutManager *)lm
                                         withBoolean:(jboolean)smoothScrollbarEnabled
                                         withBoolean:(jboolean)reverseLayout;

/*!
 @param startChild View closest to start of the list. (top or left)
 @param endChild View closest to end of the list (bottom or right)
 */
+ (jint)computeScrollRangeWithADXRecyclerView_State:(ADXRecyclerView_State *)state
                           withADXOrientationHelper:(ADXOrientationHelper *)orientation
                                         withADView:(ADView *)startChild
                                         withADView:(ADView *)endChild
                  withADXRecyclerView_LayoutManager:(ADXRecyclerView_LayoutManager *)lm
                                        withBoolean:(jboolean)smoothScrollbarEnabled;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ADXScrollbarHelper)

FOUNDATION_EXPORT jint ADXScrollbarHelper_computeScrollOffsetWithADXRecyclerView_State_withADXOrientationHelper_withADView_withADView_withADXRecyclerView_LayoutManager_withBoolean_withBoolean_(ADXRecyclerView_State *state, ADXOrientationHelper *orientation, ADView *startChild, ADView *endChild, ADXRecyclerView_LayoutManager *lm, jboolean smoothScrollbarEnabled, jboolean reverseLayout);

FOUNDATION_EXPORT jint ADXScrollbarHelper_computeScrollExtentWithADXRecyclerView_State_withADXOrientationHelper_withADView_withADView_withADXRecyclerView_LayoutManager_withBoolean_(ADXRecyclerView_State *state, ADXOrientationHelper *orientation, ADView *startChild, ADView *endChild, ADXRecyclerView_LayoutManager *lm, jboolean smoothScrollbarEnabled);

FOUNDATION_EXPORT jint ADXScrollbarHelper_computeScrollRangeWithADXRecyclerView_State_withADXOrientationHelper_withADView_withADView_withADXRecyclerView_LayoutManager_withBoolean_(ADXRecyclerView_State *state, ADXOrientationHelper *orientation, ADView *startChild, ADView *endChild, ADXRecyclerView_LayoutManager *lm, jboolean smoothScrollbarEnabled);

J2OBJC_TYPE_LITERAL_HEADER(ADXScrollbarHelper)

@compatibility_alias AndroidxRecyclerviewWidgetScrollbarHelper ADXScrollbarHelper;

#endif

#pragma pop_macro("INCLUDE_ALL_ScrollbarHelper")
