//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-javafx-widget\SWTAndroidXRecyclerView\src\main\java\com\xwray\groupie\SpanSizeProvider.java
//

#include "J2ObjC_source.h"
#include "SpanSizeProvider.h"


@interface ADXSpanSizeProvider : NSObject

@end

@implementation ADXSpanSizeProvider

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "I", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getSpanSizeWithInt:withInt:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "getSpanSize", "II" };
  static const J2ObjcClassInfo _ADXSpanSizeProvider = { "SpanSizeProvider", "com.xwray.groupie", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_ADXSpanSizeProvider;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ADXSpanSizeProvider)
