//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-javafx-widget\SWTAndroidX-core\src\main\java\androidx\annotation\VisibleForTesting.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "VisibleForTesting.h"


@implementation ADXVisibleForTesting

- (IOSClass *)annotationType {
  return ADXVisibleForTesting_class_();
}

- (NSString *)description {
  return @"@androidx.annotation.VisibleForTesting()";
}

- (jboolean)isEqual:(id)obj {
  return JreAnnotationEquals(self, obj);
}

- (NSUInteger)hash {
  return JreAnnotationHashCode(self);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _ADXVisibleForTesting = { "VisibleForTesting", "androidx.annotation", NULL, NULL, NULL, 7, 0x2609, 0, 0, -1, -1, -1, -1, -1 };
  return &_ADXVisibleForTesting;
}

@end

id<ADXVisibleForTesting> create_ADXVisibleForTesting() {
  ADXVisibleForTesting *self = AUTORELEASE([[ADXVisibleForTesting alloc] init]);
  return self;
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ADXVisibleForTesting)
