//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-javafx-widget\SWTAndroidToolBar\src\main\java\androidx\appcompat\widget\MenuParser.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_MenuParser")
#ifdef RESTRICT_MenuParser
#define INCLUDE_ALL_MenuParser 0
#else
#define INCLUDE_ALL_MenuParser 1
#endif
#undef RESTRICT_MenuParser

#if !defined (ADXMenuParser_) && (INCLUDE_ALL_MenuParser || defined(INCLUDE_ADXMenuParser))
#define ADXMenuParser_

@class ADXMenuBuilder;
@protocol ASIFragment;

@interface ADXMenuParser : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)parseMenuWithADXMenuBuilder:(ADXMenuBuilder *)menu
                       withNSString:(NSString *)json
                    withASIFragment:(id<ASIFragment>)fragment;

@end

J2OBJC_EMPTY_STATIC_INIT(ADXMenuParser)

FOUNDATION_EXPORT void ADXMenuParser_init(ADXMenuParser *self);

FOUNDATION_EXPORT ADXMenuParser *new_ADXMenuParser_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ADXMenuParser *create_ADXMenuParser_init(void);

FOUNDATION_EXPORT void ADXMenuParser_parseMenuWithADXMenuBuilder_withNSString_withASIFragment_(ADXMenuBuilder *menu, NSString *json, id<ASIFragment> fragment);

J2OBJC_TYPE_LITERAL_HEADER(ADXMenuParser)

@compatibility_alias AndroidxAppcompatWidgetMenuParser ADXMenuParser;

#endif

#pragma pop_macro("INCLUDE_ALL_MenuParser")
