//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-widget_library\widget_library\src\com\ashera\model\MethodHandler.java
//

#include "J2ObjC_source.h"
#include "MethodHandler.h"


@interface ASMethodHandler : NSObject

@end

NSString *ASMethodHandler_UNHANDLED = @"~~UNHANDLER~~";

@implementation ASMethodHandler

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSObject;", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(handleWithNSString:withId:withASIWidget:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "UNHANDLED", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 2, -1, -1 },
  };
  static const void *ptrTable[] = { "handle", "LNSString;LNSObject;LASIWidget;", &ASMethodHandler_UNHANDLED };
  static const J2ObjcClassInfo _ASMethodHandler = { "MethodHandler", "com.ashera.model", ptrTable, methods, fields, 7, 0x609, 1, 1, -1, -1, -1, -1, -1 };
  return &_ASMethodHandler;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ASMethodHandler)
