//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-widget_library\widget_library\src\com\ashera\widget\OnLayoutEvent.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OnLayoutEvent")
#ifdef RESTRICT_OnLayoutEvent
#define INCLUDE_ALL_OnLayoutEvent 0
#else
#define INCLUDE_ALL_OnLayoutEvent 1
#endif
#undef RESTRICT_OnLayoutEvent

#if !defined (ASOnLayoutEvent_) && (INCLUDE_ALL_OnLayoutEvent || defined(INCLUDE_ASOnLayoutEvent))
#define ASOnLayoutEvent_

#define RESTRICT_WidgetEvent 1
#define INCLUDE_ASWidgetEvent 1
#include "WidgetEvent.h"

@interface ASOnLayoutEvent : ASWidgetEvent

#pragma mark Public

- (instancetype)init;

- (jint)getB;

- (jint)getL;

- (jint)getR;

- (jint)getT;

- (jboolean)isChanged;

- (void)setBWithInt:(jint)b;

- (void)setChangedWithBoolean:(jboolean)changed;

- (void)setLWithInt:(jint)l;

- (void)setRWithInt:(jint)r;

- (void)setTWithInt:(jint)t;

@end

J2OBJC_EMPTY_STATIC_INIT(ASOnLayoutEvent)

FOUNDATION_EXPORT void ASOnLayoutEvent_init(ASOnLayoutEvent *self);

FOUNDATION_EXPORT ASOnLayoutEvent *new_ASOnLayoutEvent_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASOnLayoutEvent *create_ASOnLayoutEvent_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASOnLayoutEvent)

@compatibility_alias ComAsheraWidgetOnLayoutEvent ASOnLayoutEvent;

#endif

#pragma pop_macro("INCLUDE_ALL_OnLayoutEvent")
