//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\ios_widget_library\src\main\java\com\ashera\layout\UITextViewLabelImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_UITextViewLabelImpl")
#ifdef RESTRICT_UITextViewLabelImpl
#define INCLUDE_ALL_UITextViewLabelImpl 0
#else
#define INCLUDE_ALL_UITextViewLabelImpl 1
#endif
#undef RESTRICT_UITextViewLabelImpl

#if !defined (ASUITextViewLabelImpl_) && (INCLUDE_ALL_UITextViewLabelImpl || defined(INCLUDE_ASUITextViewLabelImpl))
#define ASUITextViewLabelImpl_

#define RESTRICT_BaseWidget 1
#define INCLUDE_ASBaseWidget 1
#include "BaseWidget.h"

#define RESTRICT_ValidationErrorLabel 1
#define INCLUDE_ASValidationErrorLabel 1
#include "ValidationErrorLabel.h"

@class ASMeasurableTextView;
@class ASUITextViewLabelImpl_UITextViewLabelBean;
@class ASUITextViewLabelImpl_UITextViewLabelCommandBuilder;
@class ASWidgetAttribute;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASUITextViewLabelImpl : ASBaseWidget < ASValidationErrorLabel > {
 @public
  id uiView_;
  ASMeasurableTextView *measurableTextView_;
}
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)drawableStateChanged;

- (id)getAllowsEditingTextAttributes;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (jint)getBaseLine;

- (ASUITextViewLabelImpl_UITextViewLabelBean *)getBean;

- (jint)getBorderPadding;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)getBuilder;

- (id)getClearsOnInsertion;

- (id)getIsEditable;

- (id)getIsSelectable;

- (jint)getLineHeightPadding;

- (jint)getMaxEms;

- (jint)getMaxHeight;

- (jint)getMaxLines;

- (jint)getMaxWidth;

- (jint)getMinEms;

- (jint)getMinLines;

- (id)getPaddingBottom;

- (id)getPaddingLeft;

- (id)getPaddingRight;

- (id)getPaddingTop;

- (id)getPluginWithNSString:(NSString *)plugin;

- (id)getText;

- (id)getTextColor;

- (id)getUsesStandardTextScaling;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)attributeName;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (void)onRtlPropertiesChangedWithInt:(jint)layoutDirection;

- (void)requestLayout;

- (void)setAllowsEditingTextAttributesWithId:(id)nativeWidget
                                      withId:(id)value;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setClearsOnInsertionWithId:(id)nativeWidget
                            withId:(id)value;

- (void)setErrorMessageWithNSString:(NSString *)message;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setIsEditableWithId:(id)nativeWidget
                     withId:(id)value;

- (void)setIsSelectableWithId:(id)nativeWidget
                       withId:(id)value;

- (void)setPaddingBottomWithId:(id)paddingBottom;

- (void)setPaddingLeftWithId:(id)paddingLeft;

- (void)setPaddingRightWithId:(id)paddingRight;

- (void)setPaddingTopWithId:(id)paddingTop;

- (void)setTextWithId:(id)nativeWidget
               withId:(id)value;

- (void)setTextColorWithId:(id)nativeWidget
                    withId:(id)value;

- (void)setUsesStandardTextScalingWithId:(id)nativeWidget
                                  withId:(id)value;

+ (NSString *)toUpperCaseWithNSString:(NSString *)text;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

- (void)updatePadding;

#pragma mark Package-Private

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0
                    withNSString:(NSString *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(ASUITextViewLabelImpl)

J2OBJC_FIELD_SETTER(ASUITextViewLabelImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASUITextViewLabelImpl, measurableTextView_, ASMeasurableTextView *)

inline NSString *ASUITextViewLabelImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASUITextViewLabelImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASUITextViewLabelImpl, LOCAL_NAME, NSString *)

inline NSString *ASUITextViewLabelImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASUITextViewLabelImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASUITextViewLabelImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASUITextViewLabelImpl_init(ASUITextViewLabelImpl *self);

FOUNDATION_EXPORT ASUITextViewLabelImpl *new_ASUITextViewLabelImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewLabelImpl *create_ASUITextViewLabelImpl_init(void);

FOUNDATION_EXPORT NSString *ASUITextViewLabelImpl_toUpperCaseWithNSString_(NSString *text);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewLabelImpl)

@compatibility_alias ComAsheraLayoutUITextViewLabelImpl ASUITextViewLabelImpl;

#endif

#if !defined (ASUITextViewLabelImpl_AutoSizeTextType_) && (INCLUDE_ALL_UITextViewLabelImpl || defined(INCLUDE_ASUITextViewLabelImpl_AutoSizeTextType))
#define ASUITextViewLabelImpl_AutoSizeTextType_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewLabelImpl_AutoSizeTextType : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewLabelImpl_AutoSizeTextType)

FOUNDATION_EXPORT void ASUITextViewLabelImpl_AutoSizeTextType_init(ASUITextViewLabelImpl_AutoSizeTextType *self);

FOUNDATION_EXPORT ASUITextViewLabelImpl_AutoSizeTextType *new_ASUITextViewLabelImpl_AutoSizeTextType_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewLabelImpl_AutoSizeTextType *create_ASUITextViewLabelImpl_AutoSizeTextType_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewLabelImpl_AutoSizeTextType)

#endif

#if !defined (ASUITextViewLabelImpl_Ellipsize_) && (INCLUDE_ALL_UITextViewLabelImpl || defined(INCLUDE_ASUITextViewLabelImpl_Ellipsize))
#define ASUITextViewLabelImpl_Ellipsize_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewLabelImpl_Ellipsize : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewLabelImpl_Ellipsize)

FOUNDATION_EXPORT void ASUITextViewLabelImpl_Ellipsize_init(ASUITextViewLabelImpl_Ellipsize *self);

FOUNDATION_EXPORT ASUITextViewLabelImpl_Ellipsize *new_ASUITextViewLabelImpl_Ellipsize_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewLabelImpl_Ellipsize *create_ASUITextViewLabelImpl_Ellipsize_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewLabelImpl_Ellipsize)

#endif

#if !defined (ASUITextViewLabelImpl_MarqueeRepeatLimit_) && (INCLUDE_ALL_UITextViewLabelImpl || defined(INCLUDE_ASUITextViewLabelImpl_MarqueeRepeatLimit))
#define ASUITextViewLabelImpl_MarqueeRepeatLimit_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewLabelImpl_MarqueeRepeatLimit : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

- (jboolean)supportsIntAlso;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewLabelImpl_MarqueeRepeatLimit)

FOUNDATION_EXPORT void ASUITextViewLabelImpl_MarqueeRepeatLimit_init(ASUITextViewLabelImpl_MarqueeRepeatLimit *self);

FOUNDATION_EXPORT ASUITextViewLabelImpl_MarqueeRepeatLimit *new_ASUITextViewLabelImpl_MarqueeRepeatLimit_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewLabelImpl_MarqueeRepeatLimit *create_ASUITextViewLabelImpl_MarqueeRepeatLimit_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewLabelImpl_MarqueeRepeatLimit)

#endif

#if !defined (ASUITextViewLabelImpl_JustificationMode_) && (INCLUDE_ALL_UITextViewLabelImpl || defined(INCLUDE_ASUITextViewLabelImpl_JustificationMode))
#define ASUITextViewLabelImpl_JustificationMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewLabelImpl_JustificationMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewLabelImpl_JustificationMode)

FOUNDATION_EXPORT void ASUITextViewLabelImpl_JustificationMode_init(ASUITextViewLabelImpl_JustificationMode *self);

FOUNDATION_EXPORT ASUITextViewLabelImpl_JustificationMode *new_ASUITextViewLabelImpl_JustificationMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewLabelImpl_JustificationMode *create_ASUITextViewLabelImpl_JustificationMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewLabelImpl_JustificationMode)

#endif

#if !defined (ASUITextViewLabelImpl_AutoLink_) && (INCLUDE_ALL_UITextViewLabelImpl || defined(INCLUDE_ASUITextViewLabelImpl_AutoLink))
#define ASUITextViewLabelImpl_AutoLink_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewLabelImpl_AutoLink : ASAbstractBitFlagConverter

#pragma mark Public

- (NSString *)getAllOption;

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewLabelImpl_AutoLink)

FOUNDATION_EXPORT void ASUITextViewLabelImpl_AutoLink_init(ASUITextViewLabelImpl_AutoLink *self);

FOUNDATION_EXPORT ASUITextViewLabelImpl_AutoLink *new_ASUITextViewLabelImpl_AutoLink_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewLabelImpl_AutoLink *create_ASUITextViewLabelImpl_AutoLink_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewLabelImpl_AutoLink)

#endif

#if !defined (ASUITextViewLabelImpl_Font_) && (INCLUDE_ALL_UITextViewLabelImpl || defined(INCLUDE_ASUITextViewLabelImpl_Font))
#define ASUITextViewLabelImpl_Font_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewLabelImpl_Font : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewLabelImpl_Font)

FOUNDATION_EXPORT void ASUITextViewLabelImpl_Font_init(ASUITextViewLabelImpl_Font *self);

FOUNDATION_EXPORT ASUITextViewLabelImpl_Font *new_ASUITextViewLabelImpl_Font_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewLabelImpl_Font *create_ASUITextViewLabelImpl_Font_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewLabelImpl_Font)

#endif

#if !defined (ASUITextViewLabelImpl_TextStyle_) && (INCLUDE_ALL_UITextViewLabelImpl || defined(INCLUDE_ASUITextViewLabelImpl_TextStyle))
#define ASUITextViewLabelImpl_TextStyle_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewLabelImpl_TextStyle : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewLabelImpl_TextStyle)

FOUNDATION_EXPORT void ASUITextViewLabelImpl_TextStyle_init(ASUITextViewLabelImpl_TextStyle *self);

FOUNDATION_EXPORT ASUITextViewLabelImpl_TextStyle *new_ASUITextViewLabelImpl_TextStyle_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewLabelImpl_TextStyle *create_ASUITextViewLabelImpl_TextStyle_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewLabelImpl_TextStyle)

#endif

#if !defined (ASUITextViewLabelImpl_DrawableTintMode_) && (INCLUDE_ALL_UITextViewLabelImpl || defined(INCLUDE_ASUITextViewLabelImpl_DrawableTintMode))
#define ASUITextViewLabelImpl_DrawableTintMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewLabelImpl_DrawableTintMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewLabelImpl_DrawableTintMode)

FOUNDATION_EXPORT void ASUITextViewLabelImpl_DrawableTintMode_init(ASUITextViewLabelImpl_DrawableTintMode *self);

FOUNDATION_EXPORT ASUITextViewLabelImpl_DrawableTintMode *new_ASUITextViewLabelImpl_DrawableTintMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewLabelImpl_DrawableTintMode *create_ASUITextViewLabelImpl_DrawableTintMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewLabelImpl_DrawableTintMode)

#endif

#if !defined (ASUITextViewLabelImpl_UITextViewLabelExt_) && (INCLUDE_ALL_UITextViewLabelImpl || defined(INCLUDE_ASUITextViewLabelImpl_UITextViewLabelExt))
#define ASUITextViewLabelImpl_UITextViewLabelExt_

#define RESTRICT_MeasurableTextView 1
#define INCLUDE_ASMeasurableTextView 1
#include "MeasurableTextView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

@class ADRectF;
@class ASUITextViewLabelImpl;
@class ASWidgetAttribute;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASUITextViewLabelImpl_UITextViewLabelExt : ASMeasurableTextView < ASILifeCycleDecorator >

#pragma mark Public

- (instancetype)initWithASUITextViewLabelImpl:(ASUITextViewLabelImpl *)outer$;

- (void)drawableStateChanged;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (jint)getBorderPadding;

- (jint)getBorderWidth;

- (jint)getLineHeight;

- (jint)getLineHeightPadding;

- (id<JavaUtilList>)getMethods;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)onRtlPropertiesChangedWithInt:(jint)layoutDirection;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setVisibilityWithInt:(jint)visibility;

- (jboolean)suggestedSizeFitsInSpaceWithInt:(jint)mAutoSizeTextSizeInPx
                                withADRectF:(ADRectF *)availableSpace;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

- (void)setTextSizeInternalWithInt:(jint)unit
                         withFloat:(jfloat)optimalTextSize
                       withBoolean:(jboolean)b;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewLabelImpl_UITextViewLabelExt)

FOUNDATION_EXPORT void ASUITextViewLabelImpl_UITextViewLabelExt_initWithASUITextViewLabelImpl_(ASUITextViewLabelImpl_UITextViewLabelExt *self, ASUITextViewLabelImpl *outer$);

FOUNDATION_EXPORT ASUITextViewLabelImpl_UITextViewLabelExt *new_ASUITextViewLabelImpl_UITextViewLabelExt_initWithASUITextViewLabelImpl_(ASUITextViewLabelImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewLabelImpl_UITextViewLabelExt *create_ASUITextViewLabelImpl_UITextViewLabelExt_initWithASUITextViewLabelImpl_(ASUITextViewLabelImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewLabelImpl_UITextViewLabelExt)

#endif

#if !defined (ASUITextViewLabelImpl_PostMeasureHandler_) && (INCLUDE_ALL_UITextViewLabelImpl || defined(INCLUDE_ASUITextViewLabelImpl_PostMeasureHandler))
#define ASUITextViewLabelImpl_PostMeasureHandler_

#define RESTRICT_EventBusHandler 1
#define INCLUDE_ASEventBusHandler 1
#include "EventBusHandler.h"

@class ASUITextViewLabelImpl;

@interface ASUITextViewLabelImpl_PostMeasureHandler : ASEventBusHandler

#pragma mark Public

- (instancetype)initWithASUITextViewLabelImpl:(ASUITextViewLabelImpl *)outer$
                                 withNSString:(NSString *)type;

#pragma mark Protected

- (void)doPerformWithId:(id)payload;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewLabelImpl_PostMeasureHandler)

FOUNDATION_EXPORT void ASUITextViewLabelImpl_PostMeasureHandler_initWithASUITextViewLabelImpl_withNSString_(ASUITextViewLabelImpl_PostMeasureHandler *self, ASUITextViewLabelImpl *outer$, NSString *type);

FOUNDATION_EXPORT ASUITextViewLabelImpl_PostMeasureHandler *new_ASUITextViewLabelImpl_PostMeasureHandler_initWithASUITextViewLabelImpl_withNSString_(ASUITextViewLabelImpl *outer$, NSString *type) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewLabelImpl_PostMeasureHandler *create_ASUITextViewLabelImpl_PostMeasureHandler_initWithASUITextViewLabelImpl_withNSString_(ASUITextViewLabelImpl *outer$, NSString *type);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewLabelImpl_PostMeasureHandler)

#endif

#if !defined (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder_) && (INCLUDE_ALL_UITextViewLabelImpl || defined(INCLUDE_ASUITextViewLabelImpl_UITextViewLabelCommandBuilder))
#define ASUITextViewLabelImpl_UITextViewLabelCommandBuilder_

#define RESTRICT_ViewImpl 1
#define INCLUDE_ASViewImpl_ViewCommandBuilder 1
#include "ViewImpl.h"

@class ASUITextViewLabelImpl;

@interface ASUITextViewLabelImpl_UITextViewLabelCommandBuilder : ASViewImpl_ViewCommandBuilder

#pragma mark Public

- (instancetype)initWithASUITextViewLabelImpl:(ASUITextViewLabelImpl *)outer$;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (id)getAutoLink;

- (id)getAutoSizeMaxTextSize;

- (id)getAutoSizeMinTextSize;

- (id)getAutoSizeStepGranularity;

- (id)getAutoSizeTextType;

- (id)getDrawablePadding;

- (id)getEllipsize;

- (id)getFirstBaselineToTopHeight;

- (id)getGravity;

- (id)getHeight;

- (id)getIosText;

- (id)getIosTextColor;

- (id)getJustificationMode;

- (id)getLastBaselineToBottomHeight;

- (id)getMarqueeRepeatLimit;

- (id)getMaxEms;

- (id)getMaxHeight;

- (id)getMaxLines;

- (id)getMaxWidth;

- (id)getMinEms;

- (id)getMinHeight;

- (id)getMinLines;

- (id)getMinWidth;

- (id)getPaddingBottom;

- (id)getPaddingEnd;

- (id)getPaddingLeft;

- (id)getPaddingRight;

- (id)getPaddingStart;

- (id)getPaddingTop;

- (id)getText;

- (id)getTextColor;

- (id)getTextColorHighlight;

- (id)getTextIsSelectable;

- (id)getTextSize;

- (id)getWidth;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)invalidate;

- (id)isIosAllowsEditingTextAttributes;

- (id)isIosClearsOnInsertion;

- (id)isIosIsEditable;

- (id)isIosIsSelectable;

- (id)isIosUsesStandardTextScaling;

- (id)isLinksClickable;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)requestLayout;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)reset;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setAutoLinkWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setAutoSizeMaxTextSizeWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setAutoSizeMinTextSizeWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setAutoSizePresetSizesWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setAutoSizeStepGranularityWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setAutoSizeTextTypeWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setDrawableBottomWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setDrawableEndWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setDrawableLeftWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setDrawablePaddingWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setDrawableRightWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setDrawableStartWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setDrawableTintWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setDrawableTintModeWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setDrawableTopWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setEditableWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setEllipsizeWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setEmsWithInt:(jint)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setEnabledWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setFirstBaselineToTopHeightWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setFontFamilyWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setGravityWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setHeightWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosAllowsEditingTextAttributesWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosClearsOnInsertionWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosIsEditableWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosIsSelectableWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosTextWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosTextColorWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setIosUsesStandardTextScalingWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setJustificationModeWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setLastBaselineToBottomHeightWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setLinesWithInt:(jint)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setLinksClickableWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setMarqueeRepeatLimitWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setMaxEmsWithInt:(jint)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setMaxHeightWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setMaxLengthWithInt:(jint)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setMaxLinesWithInt:(jint)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setMaxWidthWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setMinEmsWithInt:(jint)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setMinHeightWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setMinLinesWithInt:(jint)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setMinWidthWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setPaddingWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setPaddingBottomWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setPaddingEndWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setPaddingLeftWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setPaddingRightWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setPaddingStartWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setPaddingTopWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setPasswordWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setScrollHorizontallyWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setSingleLineWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setStartOrStopMarqueeWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTextWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTextAllCapsWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTextColorWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTextColorHighlightWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTextColorLinkWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTextFormatWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTextIsSelectableWithBoolean:(jboolean)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTextSizeWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTextStyleWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setTypefaceWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setWidthWithNSString:(NSString *)value;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetAlpha;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetAutoLink;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetAutoSizeMaxTextSize;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetAutoSizeMinTextSize;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetAutoSizeStepGranularity;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetAutoSizeTextType;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetBackground;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetBackgroundTint;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetBackgroundTintMode;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetClickable;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetContentDescription;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetDrawablePadding;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetDuplicateParentState;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetEllipsize;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetEnabled;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetFirstBaselineToTopHeight;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetFocusable;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetForeground;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetForegroundGravity;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetForegroundTint;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetForegroundTintMode;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetGravity;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetHeight;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetId;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosAccessibilityHint;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosAccessibilityValue;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosAllowsEditingTextAttributes;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosAlpha;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosBackgroundColor;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosClearsOnInsertion;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosClipsToBounds;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosContentScaleFactor;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosIsEditable;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosIsFocused;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosIsHidden;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosIsOpaque;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosIsSelectable;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosLargeContentImage;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosLargeContentTitle;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosTag;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosText;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosTextColor;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosTintColor;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetIosUsesStandardTextScaling;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetJustificationMode;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetKeepScreenOn;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetLastBaselineToBottomHeight;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetLayoutDirection;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetLinksClickable;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetLongClickable;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetMarqueeRepeatLimit;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetMaxEms;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetMaxHeight;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetMaxLines;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetMaxWidth;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetMinEms;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetMinHeight;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetMinLines;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetMinWidth;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetModelParam;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetModelPojoToUi;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetModelSyncEvents;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetModelUiToPojo;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetPaddingBottom;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetPaddingEnd;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetPaddingLeft;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetPaddingRight;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetPaddingStart;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetPaddingTop;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetRotation;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetRotationX;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetRotationY;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetScaleX;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetScaleY;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetSelected;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetText;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetTextAlignment;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetTextColor;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetTextColorHighlight;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetTextDirection;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetTextIsSelectable;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetTextSize;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetTransformPivotX;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetTransformPivotY;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetTranslationX;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetTranslationY;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetTranslationZ;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetValidateForm;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetVisibility;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)tryGetWidth;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                              withId:(id)arg1;

- (ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewLabelImpl_UITextViewLabelCommandBuilder)

FOUNDATION_EXPORT void ASUITextViewLabelImpl_UITextViewLabelCommandBuilder_initWithASUITextViewLabelImpl_(ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *self, ASUITextViewLabelImpl *outer$);

FOUNDATION_EXPORT ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *new_ASUITextViewLabelImpl_UITextViewLabelCommandBuilder_initWithASUITextViewLabelImpl_(ASUITextViewLabelImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewLabelImpl_UITextViewLabelCommandBuilder *create_ASUITextViewLabelImpl_UITextViewLabelCommandBuilder_initWithASUITextViewLabelImpl_(ASUITextViewLabelImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewLabelImpl_UITextViewLabelCommandBuilder)

#endif

#if !defined (ASUITextViewLabelImpl_UITextViewLabelBean_) && (INCLUDE_ALL_UITextViewLabelImpl || defined(INCLUDE_ASUITextViewLabelImpl_UITextViewLabelBean))
#define ASUITextViewLabelImpl_UITextViewLabelBean_

#define RESTRICT_ViewImpl 1
#define INCLUDE_ASViewImpl_ViewBean 1
#include "ViewImpl.h"

@class ASUITextViewLabelImpl;
@protocol ASIWidget;

@interface ASUITextViewLabelImpl_UITextViewLabelBean : ASViewImpl_ViewBean

#pragma mark Public

- (instancetype)initWithASUITextViewLabelImpl:(ASUITextViewLabelImpl *)outer$;

- (id)getAutoLink;

- (id)getAutoSizeMaxTextSize;

- (id)getAutoSizeMinTextSize;

- (id)getAutoSizeStepGranularity;

- (id)getAutoSizeTextType;

- (id)getDrawablePadding;

- (id)getEllipsize;

- (id)getFirstBaselineToTopHeight;

- (id)getGravity;

- (id)getHeight;

- (id)getIosText;

- (id)getIosTextColor;

- (id)getJustificationMode;

- (id)getLastBaselineToBottomHeight;

- (id)getMarqueeRepeatLimit;

- (id)getMaxEms;

- (id)getMaxHeight;

- (id)getMaxLines;

- (id)getMaxWidth;

- (id)getMinEms;

- (id)getMinHeight;

- (id)getMinLines;

- (id)getMinWidth;

- (id)getPaddingBottom;

- (id)getPaddingEnd;

- (id)getPaddingLeft;

- (id)getPaddingRight;

- (id)getPaddingStart;

- (id)getPaddingTop;

- (id)getText;

- (id)getTextColor;

- (id)getTextColorHighlight;

- (id)getTextIsSelectable;

- (id)getTextSize;

- (id)getWidth;

- (id)isIosAllowsEditingTextAttributes;

- (id)isIosClearsOnInsertion;

- (id)isIosIsEditable;

- (id)isIosIsSelectable;

- (id)isIosUsesStandardTextScaling;

- (id)isLinksClickable;

- (void)setAutoLinkWithNSString:(NSString *)value;

- (void)setAutoSizeMaxTextSizeWithNSString:(NSString *)value;

- (void)setAutoSizeMinTextSizeWithNSString:(NSString *)value;

- (void)setAutoSizePresetSizesWithNSString:(NSString *)value;

- (void)setAutoSizeStepGranularityWithNSString:(NSString *)value;

- (void)setAutoSizeTextTypeWithNSString:(NSString *)value;

- (void)setDrawableBottomWithNSString:(NSString *)value;

- (void)setDrawableEndWithNSString:(NSString *)value;

- (void)setDrawableLeftWithNSString:(NSString *)value;

- (void)setDrawablePaddingWithNSString:(NSString *)value;

- (void)setDrawableRightWithNSString:(NSString *)value;

- (void)setDrawableStartWithNSString:(NSString *)value;

- (void)setDrawableTintWithNSString:(NSString *)value;

- (void)setDrawableTintModeWithNSString:(NSString *)value;

- (void)setDrawableTopWithNSString:(NSString *)value;

- (void)setEditableWithBoolean:(jboolean)value;

- (void)setEllipsizeWithNSString:(NSString *)value;

- (void)setEmsWithInt:(jint)value;

- (void)setEnabledWithBoolean:(jboolean)value;

- (void)setFirstBaselineToTopHeightWithNSString:(NSString *)value;

- (void)setFontFamilyWithNSString:(NSString *)value;

- (void)setGravityWithNSString:(NSString *)value;

- (void)setHeightWithNSString:(NSString *)value;

- (void)setIosAllowsEditingTextAttributesWithBoolean:(jboolean)value;

- (void)setIosClearsOnInsertionWithBoolean:(jboolean)value;

- (void)setIosIsEditableWithBoolean:(jboolean)value;

- (void)setIosIsSelectableWithBoolean:(jboolean)value;

- (void)setIosTextWithNSString:(NSString *)value;

- (void)setIosTextColorWithNSString:(NSString *)value;

- (void)setIosUsesStandardTextScalingWithBoolean:(jboolean)value;

- (void)setJustificationModeWithNSString:(NSString *)value;

- (void)setLastBaselineToBottomHeightWithNSString:(NSString *)value;

- (void)setLinesWithInt:(jint)value;

- (void)setLinksClickableWithBoolean:(jboolean)value;

- (void)setMarqueeRepeatLimitWithNSString:(NSString *)value;

- (void)setMaxEmsWithInt:(jint)value;

- (void)setMaxHeightWithNSString:(NSString *)value;

- (void)setMaxLengthWithInt:(jint)value;

- (void)setMaxLinesWithInt:(jint)value;

- (void)setMaxWidthWithNSString:(NSString *)value;

- (void)setMinEmsWithInt:(jint)value;

- (void)setMinHeightWithNSString:(NSString *)value;

- (void)setMinLinesWithInt:(jint)value;

- (void)setMinWidthWithNSString:(NSString *)value;

- (void)setPaddingWithNSString:(NSString *)value;

- (void)setPaddingBottomWithNSString:(NSString *)value;

- (void)setPaddingEndWithNSString:(NSString *)value;

- (void)setPaddingHorizontalWithNSString:(NSString *)value;

- (void)setPaddingLeftWithNSString:(NSString *)value;

- (void)setPaddingRightWithNSString:(NSString *)value;

- (void)setPaddingStartWithNSString:(NSString *)value;

- (void)setPaddingTopWithNSString:(NSString *)value;

- (void)setPaddingVerticalWithNSString:(NSString *)value;

- (void)setPasswordWithBoolean:(jboolean)value;

- (void)setScrollHorizontallyWithBoolean:(jboolean)value;

- (void)setSingleLineWithBoolean:(jboolean)value;

- (void)setStartOrStopMarqueeWithBoolean:(jboolean)value;

- (void)setTextWithNSString:(NSString *)value;

- (void)setTextAllCapsWithBoolean:(jboolean)value;

- (void)setTextColorWithNSString:(NSString *)value;

- (void)setTextColorHighlightWithNSString:(NSString *)value;

- (void)setTextColorLinkWithNSString:(NSString *)value;

- (void)setTextFormatWithNSString:(NSString *)value;

- (void)setTextIsSelectableWithBoolean:(jboolean)value;

- (void)setTextSizeWithNSString:(NSString *)value;

- (void)setTextStyleWithNSString:(NSString *)value;

- (void)setTypefaceWithNSString:(NSString *)value;

- (void)setWidthWithNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewLabelImpl_UITextViewLabelBean)

FOUNDATION_EXPORT void ASUITextViewLabelImpl_UITextViewLabelBean_initWithASUITextViewLabelImpl_(ASUITextViewLabelImpl_UITextViewLabelBean *self, ASUITextViewLabelImpl *outer$);

FOUNDATION_EXPORT ASUITextViewLabelImpl_UITextViewLabelBean *new_ASUITextViewLabelImpl_UITextViewLabelBean_initWithASUITextViewLabelImpl_(ASUITextViewLabelImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewLabelImpl_UITextViewLabelBean *create_ASUITextViewLabelImpl_UITextViewLabelBean_initWithASUITextViewLabelImpl_(ASUITextViewLabelImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewLabelImpl_UITextViewLabelBean)

#endif

#pragma pop_macro("INCLUDE_ALL_UITextViewLabelImpl")
