//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\ios_widget_library\src\main\java\com\ashera\layout\UITextViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_UITextViewImpl")
#ifdef RESTRICT_UITextViewImpl
#define INCLUDE_ALL_UITextViewImpl 0
#else
#define INCLUDE_ALL_UITextViewImpl 1
#endif
#undef RESTRICT_UITextViewImpl

#if !defined (ASUITextViewImpl_) && (INCLUDE_ALL_UITextViewImpl || defined(INCLUDE_ASUITextViewImpl))
#define ASUITextViewImpl_

#define RESTRICT_BaseWidget 1
#define INCLUDE_ASBaseWidget 1
#include "BaseWidget.h"

#define RESTRICT_ICustomMeasureHeight 1
#define INCLUDE_ASICustomMeasureHeight 1
#include "ICustomMeasureHeight.h"

#define RESTRICT_ICustomMeasureWidth 1
#define INCLUDE_ASICustomMeasureWidth 1
#include "ICustomMeasureWidth.h"

#define RESTRICT_FormElement 1
#define INCLUDE_ASFormElement 1
#include "FormElement.h"

@class ASMeasurableTextView;
@class ASUITextViewImpl_UITextViewBean;
@class ASUITextViewImpl_UITextViewCommandBuilder;
@class ASWidgetAttribute;
@protocol ADTextWatcher;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASUITextViewImpl : ASBaseWidget < ASICustomMeasureHeight, ASICustomMeasureWidth, ASFormElement > {
 @public
  id uiView_;
  ASMeasurableTextView *measurableTextView_;
  id hintColor_;
}
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (void)addForegroundIfNeeded;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)createWrapperViewWithId:(id)wrapperParent
                      withInt:(jint)viewtype;

- (id)createWrapperViewHolderWithInt:(jint)viewType;

- (id)createWrapperViewHolderNativeWithInt:(jint)viewType;

- (void)drawableStateChanged;

- (void)focus;

- (id)getAllowsEditingTextAttributes;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASUITextViewImpl_UITextViewBean *)getBean;

- (jint)getBorderPadding;

- (ASUITextViewImpl_UITextViewCommandBuilder *)getBuilder;

- (id)getClearsOnInsertion;

- (id)getForeground;

- (id)getIsEditable;

- (id)getIsSelectable;

- (jint)getLineHeightPadding;

- (jint)getMaxEms;

- (jint)getMaxHeight;

- (jint)getMaxLines;

- (jint)getMaxWidth;

- (jint)getMinEms;

- (jint)getMinLines;

- (id)getPaddingBottom;

- (id)getPaddingLeft;

- (id)getPaddingRight;

- (id)getPaddingTop;

- (id)getPluginWithNSString:(NSString *)plugin;

- (id)getText;

- (id<ADTextWatcher>)getTextChangedListenerWithId:(id)objValue;

- (id)getTextColor;

- (NSString *)getTextEntered;

- (id)getUsesStandardTextScaling;

- (void)invalidate;

- (jboolean)isViewVisible;

- (void)loadAttributesWithNSString:(NSString *)attributeName;

- (jint)measureHeightWithInt:(jint)width;

- (jint)measureWidth;

- (id)nativeAddForeGroundWithASIWidget:(id<ASIWidget>)w;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (void)onRtlPropertiesChangedWithInt:(jint)layoutDirection;

- (void)requestLayout;

- (void)resetError;

- (void)setAllowsEditingTextAttributesWithId:(id)nativeWidget
                                      withId:(id)value;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setClearsOnInsertionWithId:(id)nativeWidget
                            withId:(id)value;

- (void)setEnabledWithId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setIsEditableWithId:(id)nativeWidget
                     withId:(id)value;

- (void)setIsSelectableWithId:(id)nativeWidget
                       withId:(id)value;

- (void)setMyTextWithId:(id)text;

- (void)setPaddingBottomWithId:(id)paddingBottom;

- (void)setPaddingLeftWithId:(id)paddingLeft;

- (void)setPaddingRightWithId:(id)paddingRight;

- (void)setPaddingTopWithId:(id)paddingTop;

- (void)setTextWithId:(id)nativeWidget
               withId:(id)value;

- (void)setTextColorWithId:(id)nativeWidget
                    withId:(id)value;

- (void)setUsesStandardTextScalingWithId:(id)nativeWidget
                                  withId:(id)value;

- (void)showErrorWithNSString:(NSString *)message;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

- (void)updatePadding;

#pragma mark Package-Private

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0
                    withNSString:(NSString *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(ASUITextViewImpl)

J2OBJC_FIELD_SETTER(ASUITextViewImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASUITextViewImpl, measurableTextView_, ASMeasurableTextView *)
J2OBJC_FIELD_SETTER(ASUITextViewImpl, hintColor_, id)

inline NSString *ASUITextViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASUITextViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASUITextViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASUITextViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASUITextViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASUITextViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASUITextViewImpl_init(ASUITextViewImpl *self);

FOUNDATION_EXPORT ASUITextViewImpl *new_ASUITextViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewImpl *create_ASUITextViewImpl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewImpl)

@compatibility_alias ComAsheraLayoutUITextViewImpl ASUITextViewImpl;

#endif

#if !defined (ASUITextViewImpl_InputView_) && (INCLUDE_ALL_UITextViewImpl || defined(INCLUDE_ASUITextViewImpl_InputView))
#define ASUITextViewImpl_InputView_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewImpl_InputView : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewImpl_InputView)

FOUNDATION_EXPORT void ASUITextViewImpl_InputView_init(ASUITextViewImpl_InputView *self);

FOUNDATION_EXPORT ASUITextViewImpl_InputView *new_ASUITextViewImpl_InputView_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewImpl_InputView *create_ASUITextViewImpl_InputView_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewImpl_InputView)

#endif

#if !defined (ASUITextViewImpl_DrawableTintMode_) && (INCLUDE_ALL_UITextViewImpl || defined(INCLUDE_ASUITextViewImpl_DrawableTintMode))
#define ASUITextViewImpl_DrawableTintMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewImpl_DrawableTintMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewImpl_DrawableTintMode)

FOUNDATION_EXPORT void ASUITextViewImpl_DrawableTintMode_init(ASUITextViewImpl_DrawableTintMode *self);

FOUNDATION_EXPORT ASUITextViewImpl_DrawableTintMode *new_ASUITextViewImpl_DrawableTintMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewImpl_DrawableTintMode *create_ASUITextViewImpl_DrawableTintMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewImpl_DrawableTintMode)

#endif

#if !defined (ASUITextViewImpl_Font_) && (INCLUDE_ALL_UITextViewImpl || defined(INCLUDE_ASUITextViewImpl_Font))
#define ASUITextViewImpl_Font_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewImpl_Font : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewImpl_Font)

FOUNDATION_EXPORT void ASUITextViewImpl_Font_init(ASUITextViewImpl_Font *self);

FOUNDATION_EXPORT ASUITextViewImpl_Font *new_ASUITextViewImpl_Font_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewImpl_Font *create_ASUITextViewImpl_Font_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewImpl_Font)

#endif

#if !defined (ASUITextViewImpl_TextStyle_) && (INCLUDE_ALL_UITextViewImpl || defined(INCLUDE_ASUITextViewImpl_TextStyle))
#define ASUITextViewImpl_TextStyle_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewImpl_TextStyle : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewImpl_TextStyle)

FOUNDATION_EXPORT void ASUITextViewImpl_TextStyle_init(ASUITextViewImpl_TextStyle *self);

FOUNDATION_EXPORT ASUITextViewImpl_TextStyle *new_ASUITextViewImpl_TextStyle_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewImpl_TextStyle *create_ASUITextViewImpl_TextStyle_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewImpl_TextStyle)

#endif

#if !defined (ASUITextViewImpl_Capitalize_) && (INCLUDE_ALL_UITextViewImpl || defined(INCLUDE_ASUITextViewImpl_Capitalize))
#define ASUITextViewImpl_Capitalize_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewImpl_Capitalize : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewImpl_Capitalize)

FOUNDATION_EXPORT void ASUITextViewImpl_Capitalize_init(ASUITextViewImpl_Capitalize *self);

FOUNDATION_EXPORT ASUITextViewImpl_Capitalize *new_ASUITextViewImpl_Capitalize_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewImpl_Capitalize *create_ASUITextViewImpl_Capitalize_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewImpl_Capitalize)

#endif

#if !defined (ASUITextViewImpl_Numeric_) && (INCLUDE_ALL_UITextViewImpl || defined(INCLUDE_ASUITextViewImpl_Numeric))
#define ASUITextViewImpl_Numeric_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewImpl_Numeric : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewImpl_Numeric)

FOUNDATION_EXPORT void ASUITextViewImpl_Numeric_init(ASUITextViewImpl_Numeric *self);

FOUNDATION_EXPORT ASUITextViewImpl_Numeric *new_ASUITextViewImpl_Numeric_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewImpl_Numeric *create_ASUITextViewImpl_Numeric_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewImpl_Numeric)

#endif

#if !defined (ASUITextViewImpl_InputType_) && (INCLUDE_ALL_UITextViewImpl || defined(INCLUDE_ASUITextViewImpl_InputType))
#define ASUITextViewImpl_InputType_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewImpl_InputType : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewImpl_InputType)

FOUNDATION_EXPORT void ASUITextViewImpl_InputType_init(ASUITextViewImpl_InputType *self);

FOUNDATION_EXPORT ASUITextViewImpl_InputType *new_ASUITextViewImpl_InputType_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewImpl_InputType *create_ASUITextViewImpl_InputType_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewImpl_InputType)

#endif

#if !defined (ASUITextViewImpl_ImeOptions_) && (INCLUDE_ALL_UITextViewImpl || defined(INCLUDE_ASUITextViewImpl_ImeOptions))
#define ASUITextViewImpl_ImeOptions_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASUITextViewImpl_ImeOptions : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewImpl_ImeOptions)

FOUNDATION_EXPORT void ASUITextViewImpl_ImeOptions_init(ASUITextViewImpl_ImeOptions *self);

FOUNDATION_EXPORT ASUITextViewImpl_ImeOptions *new_ASUITextViewImpl_ImeOptions_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewImpl_ImeOptions *create_ASUITextViewImpl_ImeOptions_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewImpl_ImeOptions)

#endif

#if !defined (ASUITextViewImpl_UITextViewExt_) && (INCLUDE_ALL_UITextViewImpl || defined(INCLUDE_ASUITextViewImpl_UITextViewExt))
#define ASUITextViewImpl_UITextViewExt_

#define RESTRICT_MeasurableTextView 1
#define INCLUDE_ASMeasurableTextView 1
#include "MeasurableTextView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

@class ASUITextViewImpl;
@class ASWidgetAttribute;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASUITextViewImpl_UITextViewExt : ASMeasurableTextView < ASILifeCycleDecorator >

#pragma mark Public

- (instancetype)initWithASUITextViewImpl:(ASUITextViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (jint)getBorderPadding;

- (jint)getBorderWidth;

- (jint)getLineHeight;

- (jint)getLineHeightPadding;

- (id<JavaUtilList>)getMethods;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewImpl_UITextViewExt)

FOUNDATION_EXPORT void ASUITextViewImpl_UITextViewExt_initWithASUITextViewImpl_(ASUITextViewImpl_UITextViewExt *self, ASUITextViewImpl *outer$);

FOUNDATION_EXPORT ASUITextViewImpl_UITextViewExt *new_ASUITextViewImpl_UITextViewExt_initWithASUITextViewImpl_(ASUITextViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewImpl_UITextViewExt *create_ASUITextViewImpl_UITextViewExt_initWithASUITextViewImpl_(ASUITextViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewImpl_UITextViewExt)

#endif

#if !defined (ASUITextViewImpl_UITextViewCommandBuilder_) && (INCLUDE_ALL_UITextViewImpl || defined(INCLUDE_ASUITextViewImpl_UITextViewCommandBuilder))
#define ASUITextViewImpl_UITextViewCommandBuilder_

#define RESTRICT_ViewImpl 1
#define INCLUDE_ASViewImpl_ViewCommandBuilder 1
#include "ViewImpl.h"

@class ASUITextViewImpl;

@interface ASUITextViewImpl_UITextViewCommandBuilder : ASViewImpl_ViewCommandBuilder

#pragma mark Public

- (instancetype)initWithASUITextViewImpl:(ASUITextViewImpl *)outer$;

- (ASUITextViewImpl_UITextViewCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (id)getDrawablePadding;

- (id)getFirstBaselineToTopHeight;

- (id)getGravity;

- (id)getHeight;

- (id)getHint;

- (id)getImeOptions;

- (id)getInputType;

- (id)getIosText;

- (id)getIosTextColor;

- (id)getLastBaselineToBottomHeight;

- (id)getLineSpacingExtra;

- (id)getLineSpacingMultiplier;

- (id)getMaxEms;

- (id)getMaxHeight;

- (id)getMaxLines;

- (id)getMaxWidth;

- (id)getMinEms;

- (id)getMinHeight;

- (id)getMinLines;

- (id)getMinWidth;

- (id)getPaddingBottom;

- (id)getPaddingEnd;

- (id)getPaddingLeft;

- (id)getPaddingRight;

- (id)getPaddingStart;

- (id)getPaddingTop;

- (id)getText;

- (id)getTextColor;

- (id)getTextColorHighlight;

- (id)getTextIsSelectable;

- (id)getTextSize;

- (id)getWidth;

- (ASUITextViewImpl_UITextViewCommandBuilder *)invalidate;

- (id)isCursorVisible;

- (id)isIosAllowsEditingTextAttributes;

- (id)isIosClearsOnInsertion;

- (id)isIosIsEditable;

- (id)isIosIsSelectable;

- (id)isIosUsesStandardTextScaling;

- (ASUITextViewImpl_UITextViewCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)requestLayout;

- (ASUITextViewImpl_UITextViewCommandBuilder *)reset;

- (ASUITextViewImpl_UITextViewCommandBuilder *)selectAllWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)selectAllOnFocusWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setAutoTextWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setCapitalizeWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setCursorVisibleWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setDigitsWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setDrawableBottomWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setDrawableEndWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setDrawableLeftWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setDrawablePaddingWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setDrawableRightWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setDrawableStartWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setDrawableTintWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setDrawableTintModeWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setDrawableTopWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setEditableWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setEmsWithInt:(jint)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setEnabledWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setFirstBaselineToTopHeightWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setFontFamilyWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setGravityWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setHeightWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setHintWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setHintTextFormatWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setImeOptionsWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setInputTypeWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosAllowsEditingTextAttributesWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosClearsOnInsertionWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosInputAccessoryViewDoneButtonWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosInputViewWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosIsEditableWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosIsSelectableWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosTextWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosTextColorWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setIosUsesStandardTextScalingWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setLastBaselineToBottomHeightWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setLinesWithInt:(jint)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setLineSpacingExtraWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setLineSpacingMultiplierWithFloat:(jfloat)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setMaxEmsWithInt:(jint)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setMaxHeightWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setMaxLengthWithInt:(jint)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setMaxLinesWithInt:(jint)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setMaxWidthWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setMinEmsWithInt:(jint)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setMinHeightWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setMinLinesWithInt:(jint)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setMinWidthWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setNumericWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setOnafterTextChangeWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setOnbeforeTextChangeWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setOnEditorActionWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setOnFocusChangeWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setOnTextChangeWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setPaddingWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setPaddingBottomWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setPaddingEndWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setPaddingLeftWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setPaddingRightWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setPaddingStartWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setPaddingTopWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setPhoneNumberWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setScrollHorizontallyWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setSingleLineWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTextWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTextAllCapsWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTextColorWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTextColorHighlightWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTextColorHintWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTextIsSelectableWithBoolean:(jboolean)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTextSizeWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTextStyleWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setTypefaceWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setWidthWithNSString:(NSString *)value;

- (ASUITextViewImpl_UITextViewCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetAlpha;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetBackground;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetBackgroundTint;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetBackgroundTintMode;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetClickable;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetContentDescription;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetCursorVisible;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetDrawablePadding;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetDuplicateParentState;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetEnabled;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetFirstBaselineToTopHeight;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetFocusable;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetForeground;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetForegroundGravity;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetForegroundTint;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetForegroundTintMode;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetGravity;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetHeight;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetHint;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetId;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetImeOptions;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetInputType;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosAccessibilityHint;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosAccessibilityValue;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosAllowsEditingTextAttributes;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosAlpha;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosBackgroundColor;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosClearsOnInsertion;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosClipsToBounds;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosContentScaleFactor;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosIsEditable;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosIsFocused;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosIsHidden;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosIsOpaque;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosIsSelectable;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosLargeContentImage;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosLargeContentTitle;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosTag;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosText;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosTextColor;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosTintColor;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetIosUsesStandardTextScaling;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetKeepScreenOn;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetLastBaselineToBottomHeight;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetLayoutDirection;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetLineSpacingExtra;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetLineSpacingMultiplier;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetLongClickable;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetMaxEms;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetMaxHeight;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetMaxLines;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetMaxWidth;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetMinEms;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetMinHeight;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetMinLines;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetMinWidth;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetModelParam;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetModelPojoToUi;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetModelSyncEvents;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetModelUiToPojo;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetPaddingBottom;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetPaddingEnd;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetPaddingLeft;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetPaddingRight;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetPaddingStart;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetPaddingTop;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetRotation;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetRotationX;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetRotationY;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetScaleX;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetScaleY;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetSelected;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetText;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetTextAlignment;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetTextColor;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetTextColorHighlight;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetTextDirection;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetTextIsSelectable;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetTextSize;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetTransformPivotX;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetTransformPivotY;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetTranslationX;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetTranslationY;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetTranslationZ;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetValidateForm;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetVisibility;

- (ASUITextViewImpl_UITextViewCommandBuilder *)tryGetWidth;

- (ASUITextViewImpl_UITextViewCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                    withId:(id)arg1;

- (ASUITextViewImpl_UITextViewCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewImpl_UITextViewCommandBuilder)

FOUNDATION_EXPORT void ASUITextViewImpl_UITextViewCommandBuilder_initWithASUITextViewImpl_(ASUITextViewImpl_UITextViewCommandBuilder *self, ASUITextViewImpl *outer$);

FOUNDATION_EXPORT ASUITextViewImpl_UITextViewCommandBuilder *new_ASUITextViewImpl_UITextViewCommandBuilder_initWithASUITextViewImpl_(ASUITextViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewImpl_UITextViewCommandBuilder *create_ASUITextViewImpl_UITextViewCommandBuilder_initWithASUITextViewImpl_(ASUITextViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewImpl_UITextViewCommandBuilder)

#endif

#if !defined (ASUITextViewImpl_UITextViewBean_) && (INCLUDE_ALL_UITextViewImpl || defined(INCLUDE_ASUITextViewImpl_UITextViewBean))
#define ASUITextViewImpl_UITextViewBean_

#define RESTRICT_ViewImpl 1
#define INCLUDE_ASViewImpl_ViewBean 1
#include "ViewImpl.h"

@class ASUITextViewImpl;
@protocol ASIWidget;

@interface ASUITextViewImpl_UITextViewBean : ASViewImpl_ViewBean

#pragma mark Public

- (instancetype)initWithASUITextViewImpl:(ASUITextViewImpl *)outer$;

- (id)getDrawablePadding;

- (id)getFirstBaselineToTopHeight;

- (id)getGravity;

- (id)getHeight;

- (id)getHint;

- (id)getImeOptions;

- (id)getInputType;

- (id)getIosText;

- (id)getIosTextColor;

- (id)getLastBaselineToBottomHeight;

- (id)getLineSpacingExtra;

- (id)getLineSpacingMultiplier;

- (id)getMaxEms;

- (id)getMaxHeight;

- (id)getMaxLines;

- (id)getMaxWidth;

- (id)getMinEms;

- (id)getMinHeight;

- (id)getMinLines;

- (id)getMinWidth;

- (id)getPaddingBottom;

- (id)getPaddingEnd;

- (id)getPaddingLeft;

- (id)getPaddingRight;

- (id)getPaddingStart;

- (id)getPaddingTop;

- (id)getText;

- (id)getTextColor;

- (id)getTextColorHighlight;

- (id)getTextIsSelectable;

- (id)getTextSize;

- (id)getWidth;

- (id)isCursorVisible;

- (id)isIosAllowsEditingTextAttributes;

- (id)isIosClearsOnInsertion;

- (id)isIosIsEditable;

- (id)isIosIsSelectable;

- (id)isIosUsesStandardTextScaling;

- (void)selectAllWithBoolean:(jboolean)value;

- (void)selectAllOnFocusWithBoolean:(jboolean)value;

- (void)setAutoTextWithBoolean:(jboolean)value;

- (void)setCapitalizeWithNSString:(NSString *)value;

- (void)setCursorVisibleWithBoolean:(jboolean)value;

- (void)setDigitsWithNSString:(NSString *)value;

- (void)setDrawableBottomWithNSString:(NSString *)value;

- (void)setDrawableEndWithNSString:(NSString *)value;

- (void)setDrawableLeftWithNSString:(NSString *)value;

- (void)setDrawablePaddingWithNSString:(NSString *)value;

- (void)setDrawableRightWithNSString:(NSString *)value;

- (void)setDrawableStartWithNSString:(NSString *)value;

- (void)setDrawableTintWithNSString:(NSString *)value;

- (void)setDrawableTintModeWithNSString:(NSString *)value;

- (void)setDrawableTopWithNSString:(NSString *)value;

- (void)setEditableWithBoolean:(jboolean)value;

- (void)setEmsWithInt:(jint)value;

- (void)setEnabledWithBoolean:(jboolean)value;

- (void)setFirstBaselineToTopHeightWithNSString:(NSString *)value;

- (void)setFontFamilyWithNSString:(NSString *)value;

- (void)setGravityWithNSString:(NSString *)value;

- (void)setHeightWithNSString:(NSString *)value;

- (void)setHintWithNSString:(NSString *)value;

- (void)setHintTextFormatWithNSString:(NSString *)value;

- (void)setImeOptionsWithNSString:(NSString *)value;

- (void)setInputTypeWithNSString:(NSString *)value;

- (void)setIosAllowsEditingTextAttributesWithBoolean:(jboolean)value;

- (void)setIosClearsOnInsertionWithBoolean:(jboolean)value;

- (void)setIosInputAccessoryViewDoneButtonWithNSString:(NSString *)value;

- (void)setIosInputViewWithNSString:(NSString *)value;

- (void)setIosIsEditableWithBoolean:(jboolean)value;

- (void)setIosIsSelectableWithBoolean:(jboolean)value;

- (void)setIosTextWithNSString:(NSString *)value;

- (void)setIosTextColorWithNSString:(NSString *)value;

- (void)setIosUsesStandardTextScalingWithBoolean:(jboolean)value;

- (void)setLastBaselineToBottomHeightWithNSString:(NSString *)value;

- (void)setLinesWithInt:(jint)value;

- (void)setLineSpacingExtraWithNSString:(NSString *)value;

- (void)setLineSpacingMultiplierWithFloat:(jfloat)value;

- (void)setMaxEmsWithInt:(jint)value;

- (void)setMaxHeightWithNSString:(NSString *)value;

- (void)setMaxLengthWithInt:(jint)value;

- (void)setMaxLinesWithInt:(jint)value;

- (void)setMaxWidthWithNSString:(NSString *)value;

- (void)setMinEmsWithInt:(jint)value;

- (void)setMinHeightWithNSString:(NSString *)value;

- (void)setMinLinesWithInt:(jint)value;

- (void)setMinWidthWithNSString:(NSString *)value;

- (void)setNumericWithNSString:(NSString *)value;

- (void)setOnafterTextChangeWithNSString:(NSString *)value;

- (void)setOnbeforeTextChangeWithNSString:(NSString *)value;

- (void)setOnEditorActionWithNSString:(NSString *)value;

- (void)setOnFocusChangeWithNSString:(NSString *)value;

- (void)setOnTextChangeWithNSString:(NSString *)value;

- (void)setPaddingWithNSString:(NSString *)value;

- (void)setPaddingBottomWithNSString:(NSString *)value;

- (void)setPaddingEndWithNSString:(NSString *)value;

- (void)setPaddingHorizontalWithNSString:(NSString *)value;

- (void)setPaddingLeftWithNSString:(NSString *)value;

- (void)setPaddingRightWithNSString:(NSString *)value;

- (void)setPaddingStartWithNSString:(NSString *)value;

- (void)setPaddingTopWithNSString:(NSString *)value;

- (void)setPaddingVerticalWithNSString:(NSString *)value;

- (void)setPhoneNumberWithBoolean:(jboolean)value;

- (void)setScrollHorizontallyWithBoolean:(jboolean)value;

- (void)setSingleLineWithBoolean:(jboolean)value;

- (void)setTextWithNSString:(NSString *)value;

- (void)setTextAllCapsWithBoolean:(jboolean)value;

- (void)setTextColorWithNSString:(NSString *)value;

- (void)setTextColorHighlightWithNSString:(NSString *)value;

- (void)setTextColorHintWithNSString:(NSString *)value;

- (void)setTextIsSelectableWithBoolean:(jboolean)value;

- (void)setTextSizeWithNSString:(NSString *)value;

- (void)setTextStyleWithNSString:(NSString *)value;

- (void)setTypefaceWithNSString:(NSString *)value;

- (void)setWidthWithNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASUITextViewImpl_UITextViewBean)

FOUNDATION_EXPORT void ASUITextViewImpl_UITextViewBean_initWithASUITextViewImpl_(ASUITextViewImpl_UITextViewBean *self, ASUITextViewImpl *outer$);

FOUNDATION_EXPORT ASUITextViewImpl_UITextViewBean *new_ASUITextViewImpl_UITextViewBean_initWithASUITextViewImpl_(ASUITextViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASUITextViewImpl_UITextViewBean *create_ASUITextViewImpl_UITextViewBean_initWithASUITextViewImpl_(ASUITextViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASUITextViewImpl_UITextViewBean)

#endif

#pragma pop_macro("INCLUDE_ALL_UITextViewImpl")
