//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\ios_widget_library\src\main\java\com\ashera\layout\ViewGroupModelImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ViewGroupModelImpl")
#ifdef RESTRICT_ViewGroupModelImpl
#define INCLUDE_ALL_ViewGroupModelImpl 0
#else
#define INCLUDE_ALL_ViewGroupModelImpl 1
#endif
#undef RESTRICT_ViewGroupModelImpl
#ifdef INCLUDE_ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal
#define INCLUDE_ASViewGroupModelImpl_ViewGroupModelCommandBuilder 1
#endif

#if !defined (ASViewGroupModelImpl_) && (INCLUDE_ALL_ViewGroupModelImpl || defined(INCLUDE_ASViewGroupModelImpl))
#define ASViewGroupModelImpl_

@class ASWidgetAttribute;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;

@interface ASViewGroupModelImpl : NSObject

#pragma mark Public

+ (id)getAttributeWithASIWidget:(id<ASIWidget>)w
          withASWidgetAttribute:(ASWidgetAttribute *)key
      withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

+ (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

+ (jboolean)isAttributeSupportedWithASWidgetAttribute:(ASWidgetAttribute *)key;

+ (void)register__WithNSString:(NSString *)localName;

+ (void)setAttributeWithASIWidget:(id<ASIWidget>)w
            withASWidgetAttribute:(ASWidgetAttribute *)key
                     withNSString:(NSString *)strValue
                           withId:(id)objValue
        withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

+ (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                                withId:(id)objValue
                                withId:(id)layoutParams;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewGroupModelImpl)

FOUNDATION_EXPORT void ASViewGroupModelImpl_register__WithNSString_(NSString *localName);

FOUNDATION_EXPORT void ASViewGroupModelImpl_setAttributeWithASIWidget_withASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(id<ASIWidget> w, ASWidgetAttribute *key, NSString *strValue, id objValue, id<ASILifeCycleDecorator> decorator);

FOUNDATION_EXPORT void ASViewGroupModelImpl_setChildAttributeWithASIWidget_withASWidgetAttribute_withId_withId_(id<ASIWidget> w, ASWidgetAttribute *key, id objValue, id layoutParams);

FOUNDATION_EXPORT id ASViewGroupModelImpl_getAttributeWithASIWidget_withASWidgetAttribute_withASILifeCycleDecorator_(id<ASIWidget> w, ASWidgetAttribute *key, id<ASILifeCycleDecorator> decorator);

FOUNDATION_EXPORT id ASViewGroupModelImpl_getChildAttributeWithASIWidget_withASWidgetAttribute_(id<ASIWidget> w, ASWidgetAttribute *key);

FOUNDATION_EXPORT jboolean ASViewGroupModelImpl_isAttributeSupportedWithASWidgetAttribute_(ASWidgetAttribute *key);

J2OBJC_TYPE_LITERAL_HEADER(ASViewGroupModelImpl)

@compatibility_alias ComAsheraLayoutViewGroupModelImpl ASViewGroupModelImpl;

#endif

#if !defined (ASViewGroupModelImpl_ViewGroupModelCommandBuilder_) && (INCLUDE_ALL_ViewGroupModelImpl || defined(INCLUDE_ASViewGroupModelImpl_ViewGroupModelCommandBuilder))
#define ASViewGroupModelImpl_ViewGroupModelCommandBuilder_

#define RESTRICT_ViewImpl 1
#define INCLUDE_ASViewImpl_ViewCommandBuilder 1
#include "ViewImpl.h"

@interface ASViewGroupModelImpl_ViewGroupModelCommandBuilder : ASViewImpl_ViewCommandBuilder

#pragma mark Public

- (instancetype)init;

- (id)addAllModelWithId:(id)value;

- (id)addModelWithId:(id)value;

- (id)addModelByIndexWithId:(id)value
                     withId:(id)index;

- (id)getModelIdPath;

- (id)removeModelAtIndexWithInt:(jint)value;

- (id)removeModelByIdWithNSString:(NSString *)value;

- (id)setModelForWithNSString:(NSString *)value;

- (id)setModelIdPathWithNSString:(NSString *)value;

- (id)tryGetModelIdPath;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewGroupModelImpl_ViewGroupModelCommandBuilder)

FOUNDATION_EXPORT void ASViewGroupModelImpl_ViewGroupModelCommandBuilder_init(ASViewGroupModelImpl_ViewGroupModelCommandBuilder *self);

J2OBJC_TYPE_LITERAL_HEADER(ASViewGroupModelImpl_ViewGroupModelCommandBuilder)

#endif

#if !defined (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal_) && (INCLUDE_ALL_ViewGroupModelImpl || defined(INCLUDE_ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal))
#define ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal_

@protocol ASIWidget;

@interface ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal : ASViewGroupModelImpl_ViewGroupModelCommandBuilder

#pragma mark Public

- (instancetype)initWithASIWidget:(id<ASIWidget>)widget;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)addAllModelWithId:(id)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)addModelByIndexWithId:(id)arg0
                                                                              withId:(id)arg1;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)addModelWithId:(id)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)invalidate;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)removeModelAtIndexWithInt:(jint)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)requestLayout;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)reset;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setAlphaWithFloat:(jfloat)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setBackgroundWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setClickableWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setEnabledWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setFocusableWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setForegroundWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIdWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosTagWithInt:(jint)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setMinHeightWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setMinWidthWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setModelForWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setModelParamWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setOnClickWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setOnDragWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setOnKeyWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setOnTouchWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setRotationWithFloat:(jfloat)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setRotationXWithFloat:(jfloat)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setRotationYWithFloat:(jfloat)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setScaleXWithFloat:(jfloat)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setScaleYWithFloat:(jfloat)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setSelectedWithBoolean:(jboolean)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setStyleWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setTranslationXWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setTranslationYWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setTranslationZWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setV_maxWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setV_minWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setV_patternWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setV_requiredWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setV_typeWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setValidationWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setVisibilityWithNSString:(NSString *)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)setZIndexWithInt:(jint)arg0;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetAlpha;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetBackground;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetBackgroundTint;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetBackgroundTintMode;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetClickable;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetContentDescription;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetDuplicateParentState;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetEnabled;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetFocusable;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetForeground;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetForegroundGravity;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetForegroundTint;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetForegroundTintMode;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetId;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosAccessibilityHint;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosAccessibilityLabel;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosAccessibilityTraits;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosAccessibilityValue;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosAlpha;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosAutoresizesSubviews;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosBackgroundColor;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosClearsContextBeforeDrawing;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosClipsToBounds;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosContentScaleFactor;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosIsAccessibilityElement;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosIsExclusiveTouch;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosIsFocused;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosIsHidden;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosIsMultipleTouchEnabled;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosIsOpaque;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosIsUserInteractionEnabled;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosLargeContentImage;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosLargeContentTitle;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosRestorationIdentifier;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosScalesLargeContentImage;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosShowsLargeContentViewer;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosTag;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosTintColor;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetKeepScreenOn;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetLayoutDirection;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetLongClickable;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetMaxHeight;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetMaxWidth;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetMinHeight;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetMinWidth;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetModelIdPath;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetModelParam;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetModelPojoToUi;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetModelSyncEvents;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetModelUiToPojo;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetRotation;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetRotationX;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetRotationY;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetScaleX;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetScaleY;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetSelected;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetTextAlignment;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetTextDirection;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetTransformPivotX;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetTransformPivotY;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetTranslationX;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetTranslationY;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetTranslationZ;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetValidateForm;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)tryGetVisibility;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)updateModelDataWithNSString:(NSString *)arg0
                                                                                    withId:(id)arg1;

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)validateFormWithNSString:(NSString *)arg0;

#pragma mark Protected

- (ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *)executeWithBoolean:(jboolean)setter;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal)

FOUNDATION_EXPORT void ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal_initWithASIWidget_(ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *self, id<ASIWidget> widget);

FOUNDATION_EXPORT ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *new_ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal_initWithASIWidget_(id<ASIWidget> widget) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal *create_ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal_initWithASIWidget_(id<ASIWidget> widget);

J2OBJC_TYPE_LITERAL_HEADER(ASViewGroupModelImpl_ViewGroupModelCommandBuilderInternal)

#endif

#if !defined (ASViewGroupModelImpl_ViewGroupModelBean_) && (INCLUDE_ALL_ViewGroupModelImpl || defined(INCLUDE_ASViewGroupModelImpl_ViewGroupModelBean))
#define ASViewGroupModelImpl_ViewGroupModelBean_

#define RESTRICT_ViewImpl 1
#define INCLUDE_ASViewImpl_ViewBean 1
#include "ViewImpl.h"

@protocol ASIWidget;

@interface ASViewGroupModelImpl_ViewGroupModelBean : ASViewImpl_ViewBean

#pragma mark Public

- (instancetype)initWithASIWidget:(id<ASIWidget>)widget;

- (void)addAllModelWithId:(id)value;

- (void)addModelWithId:(id)value;

- (void)addModelByIndexWithId:(id)value
                       withId:(id)index;

- (id)getModelIdPath;

- (void)removeModelAtIndexWithInt:(jint)value;

- (void)removeModelByIdWithNSString:(NSString *)value;

- (void)setModelForWithNSString:(NSString *)value;

- (void)setModelIdPathWithNSString:(NSString *)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ASViewGroupModelImpl_ViewGroupModelBean)

FOUNDATION_EXPORT void ASViewGroupModelImpl_ViewGroupModelBean_initWithASIWidget_(ASViewGroupModelImpl_ViewGroupModelBean *self, id<ASIWidget> widget);

FOUNDATION_EXPORT ASViewGroupModelImpl_ViewGroupModelBean *new_ASViewGroupModelImpl_ViewGroupModelBean_initWithASIWidget_(id<ASIWidget> widget) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASViewGroupModelImpl_ViewGroupModelBean *create_ASViewGroupModelImpl_ViewGroupModelBean_initWithASIWidget_(id<ASIWidget> widget);

J2OBJC_TYPE_LITERAL_HEADER(ASViewGroupModelImpl_ViewGroupModelBean)

#endif

#pragma pop_macro("INCLUDE_ALL_ViewGroupModelImpl")
