//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-javafx-widget\SWTAndroidXConstraintLayout\src\main\java\androidx\constraintlayout\core\Cache.java
//

#include "CLPools.h"
#include "Cache.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "SolverVariable.h"


@implementation ADXCache

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ADXCache_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)dealloc {
  RELEASE_(optimizedArrayRowPool_);
  RELEASE_(arrayRowPool_);
  RELEASE_(solverVariablePool_);
  RELEASE_(mIndexedVariables_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "optimizedArrayRowPool_", "LADXCLPools_Pool;", .constantValue.asLong = 0, 0x0, -1, -1, 0, -1 },
    { "arrayRowPool_", "LADXCLPools_Pool;", .constantValue.asLong = 0, 0x0, -1, -1, 0, -1 },
    { "solverVariablePool_", "LADXCLPools_Pool;", .constantValue.asLong = 0, 0x0, -1, -1, 1, -1 },
    { "mIndexedVariables_", "[LADXSolverVariable;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "Landroidx/constraintlayout/core/CLPools$Pool<Landroidx/constraintlayout/core/ArrayRow;>;", "Landroidx/constraintlayout/core/CLPools$Pool<Landroidx/constraintlayout/core/SolverVariable;>;" };
  static const J2ObjcClassInfo _ADXCache = { "Cache", "androidx.constraintlayout.core", ptrTable, methods, fields, 7, 0x1, 1, 4, -1, -1, -1, -1, -1 };
  return &_ADXCache;
}

@end

void ADXCache_init(ADXCache *self) {
  NSObject_init(self);
  JreStrongAssignAndConsume(&self->optimizedArrayRowPool_, new_ADXCLPools_SimplePool_initWithInt_(256));
  JreStrongAssignAndConsume(&self->arrayRowPool_, new_ADXCLPools_SimplePool_initWithInt_(256));
  JreStrongAssignAndConsume(&self->solverVariablePool_, new_ADXCLPools_SimplePool_initWithInt_(256));
  JreStrongAssignAndConsume(&self->mIndexedVariables_, [IOSObjectArray newArrayWithLength:32 type:ADXSolverVariable_class_()]);
}

ADXCache *new_ADXCache_init() {
  J2OBJC_NEW_IMPL(ADXCache, init)
}

ADXCache *create_ADXCache_init() {
  J2OBJC_CREATE_IMPL(ADXCache, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ADXCache)
