//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-javafx-widget\SWTAndroidXConstraintLayout\src\main\java\androidx\constraintlayout\core\parser\CLKey.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CLKey")
#ifdef RESTRICT_CLKey
#define INCLUDE_ALL_CLKey 0
#else
#define INCLUDE_ALL_CLKey 1
#endif
#undef RESTRICT_CLKey

#if !defined (ADXCLKey_) && (INCLUDE_ALL_CLKey || defined(INCLUDE_ADXCLKey))
#define ADXCLKey_

#define RESTRICT_CLContainer 1
#define INCLUDE_ADXCLContainer 1
#include "CLContainer.h"

@class ADXCLElement;
@class IOSCharArray;

@interface ADXCLKey : ADXCLContainer

#pragma mark Public

- (instancetype)initWithCharArray:(IOSCharArray *)content;

+ (ADXCLElement *)allocateWithCharArray:(IOSCharArray *)content OBJC_METHOD_FAMILY_NONE;

+ (ADXCLElement *)allocateWithNSString:(NSString *)name
                      withADXCLElement:(ADXCLElement *)value OBJC_METHOD_FAMILY_NONE;

- (NSString *)getName;

- (ADXCLElement *)getValue;

- (void)setWithADXCLElement:(ADXCLElement *)value;

#pragma mark Protected

- (NSString *)toFormattedJSONWithInt:(jint)indent
                             withInt:(jint)forceIndent;

- (NSString *)toJSON;

@end

J2OBJC_STATIC_INIT(ADXCLKey)

FOUNDATION_EXPORT void ADXCLKey_initWithCharArray_(ADXCLKey *self, IOSCharArray *content);

FOUNDATION_EXPORT ADXCLKey *new_ADXCLKey_initWithCharArray_(IOSCharArray *content) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ADXCLKey *create_ADXCLKey_initWithCharArray_(IOSCharArray *content);

FOUNDATION_EXPORT ADXCLElement *ADXCLKey_allocateWithCharArray_(IOSCharArray *content);

FOUNDATION_EXPORT ADXCLElement *ADXCLKey_allocateWithNSString_withADXCLElement_(NSString *name, ADXCLElement *value);

J2OBJC_TYPE_LITERAL_HEADER(ADXCLKey)

@compatibility_alias AndroidxConstraintlayoutCoreParserCLKey ADXCLKey;

#endif

#pragma pop_macro("INCLUDE_ALL_CLKey")
