//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-javafx-widget\SWTAndroidXConstraintLayout\src\main\java\androidx\constraintlayout\core\motion\utils\CLRect.java
//

#include "CLRect.h"
#include "J2ObjC_source.h"


@implementation ADXCLRect

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ADXCLRect_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (jint)width {
  return right_ - left_;
}

- (jint)height {
  return bottom_ - top_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(width);
  methods[2].selector = @selector(height);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "bottom_", "I", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "left_", "I", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "right_", "I", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "top_", "I", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
  };
  static const J2ObjcClassInfo _ADXCLRect = { "CLRect", "androidx.constraintlayout.core.motion.utils", NULL, methods, fields, 7, 0x1, 3, 4, -1, -1, -1, -1, -1 };
  return &_ADXCLRect;
}

@end

void ADXCLRect_init(ADXCLRect *self) {
  NSObject_init(self);
}

ADXCLRect *new_ADXCLRect_init() {
  J2OBJC_NEW_IMPL(ADXCLRect, init)
}

ADXCLRect *create_ADXCLRect_init() {
  J2OBJC_CREATE_IMPL(ADXCLRect, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ADXCLRect)
