//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-widget_library\Plugin_Converter\src\com\ashera\validations\AlphaNumeric.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AlphaNumeric")
#ifdef RESTRICT_AlphaNumeric
#define INCLUDE_ALL_AlphaNumeric 0
#else
#define INCLUDE_ALL_AlphaNumeric 1
#endif
#undef RESTRICT_AlphaNumeric

#if !defined (ASAlphaNumeric_) && (INCLUDE_ALL_AlphaNumeric || defined(INCLUDE_ASAlphaNumeric))
#define ASAlphaNumeric_

#define RESTRICT_BaseValidator 1
#define INCLUDE_ASBaseValidator 1
#include "BaseValidator.h"

@class IOSObjectArray;
@protocol ASIWidget;
@protocol ASValidation;

/*!
 @brief Class for Alphanumeric form validation
 */
@interface ASAlphaNumeric : ASBaseValidator

#pragma mark Public

- (instancetype)init;

/*!
 @param context context
 @return error message string
 */
- (NSString *)getDefaultErrorMessageWithASIWidget:(id<ASIWidget>)widget;

/*!
 @brief checks if the field is alphanumeric value
 @param text text field
 @return isValid true or false
 */
- (jboolean)isValidWithNSString:(NSString *)text
                  withASIWidget:(id<ASIWidget>)widget;

- (id<ASValidation>)newInstanceWithNSStringArray:(IOSObjectArray *)argument OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAlphaNumeric)

FOUNDATION_EXPORT void ASAlphaNumeric_init(ASAlphaNumeric *self);

FOUNDATION_EXPORT ASAlphaNumeric *new_ASAlphaNumeric_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAlphaNumeric *create_ASAlphaNumeric_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASAlphaNumeric)

@compatibility_alias ComAsheraValidationsAlphaNumeric ASAlphaNumeric;

#endif

#pragma pop_macro("INCLUDE_ALL_AlphaNumeric")
