//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-javafx-widget\SWTAndroid\src\main\java\r\com\android\internal\util\FastMath.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_FastMath")
#ifdef RESTRICT_FastMath
#define INCLUDE_ALL_FastMath 0
#else
#define INCLUDE_ALL_FastMath 1
#endif
#undef RESTRICT_FastMath

#if !defined (ADFastMath_) && (INCLUDE_ALL_FastMath || defined(INCLUDE_ADFastMath))
#define ADFastMath_

@interface ADFastMath : NSObject

#pragma mark Public

- (instancetype)init;

+ (jint)roundWithFloat:(jfloat)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ADFastMath)

FOUNDATION_EXPORT void ADFastMath_init(ADFastMath *self);

FOUNDATION_EXPORT ADFastMath *new_ADFastMath_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ADFastMath *create_ADFastMath_init(void);

FOUNDATION_EXPORT jint ADFastMath_roundWithFloat_(jfloat value);

J2OBJC_TYPE_LITERAL_HEADER(ADFastMath)

@compatibility_alias RComAndroidInternalUtilFastMath ADFastMath;

#endif

#pragma pop_macro("INCLUDE_ALL_FastMath")
