//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-javafx-widget\SWTAndroid\src\main\java\r\android\graphics\drawable\StateListDrawable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_StateListDrawable")
#ifdef RESTRICT_StateListDrawable
#define INCLUDE_ALL_StateListDrawable 0
#else
#define INCLUDE_ALL_StateListDrawable 1
#endif
#undef RESTRICT_StateListDrawable

#if !defined (ADStateListDrawable_) && (INCLUDE_ALL_StateListDrawable || defined(INCLUDE_ADStateListDrawable))
#define ADStateListDrawable_

#define RESTRICT_Drawable 1
#define INCLUDE_ADDrawable 1
#include "Drawable.h"

@class IOSIntArray;
@protocol JavaUtilList;

@interface ADStateListDrawable : ADDrawable

#pragma mark Public

- (instancetype)init;

- (jint)addChildWithADDrawable:(ADDrawable *)dr;

- (void)addStateWithIntArray:(IOSIntArray *)stateSet
              withADDrawable:(ADDrawable *)drawable;

- (id<JavaUtilList>)getAllDrawables;

- (jint)getChildCount;

- (ADDrawable *)getCurrentDrawable;

- (id)getDrawable;

- (void)growArrayWithInt:(jint)oldSize
                 withInt:(jint)newSize;

- (void)growArrayStateSetWithInt:(jint)oldSize
                         withInt:(jint)newSize;

- (jboolean)isStateful;

+ (jboolean)isWildCardWithIntArray:(IOSIntArray *)stateSetOrSpec;

- (jboolean)selectDrawableWithInt:(jint)index;

- (void)setBoundsWithInt:(jint)left
                 withInt:(jint)top
                 withInt:(jint)right
                 withInt:(jint)bottom;

- (void)setDrawableWithId:(id)drawable;

+ (jboolean)stateSetMatchesWithIntArray:(IOSIntArray *)stateSpec
                           withIntArray:(IOSIntArray *)stateSet;

#pragma mark Protected

- (jboolean)onStateChangeWithIntArray:(IOSIntArray *)stateSet;

#pragma mark Package-Private

- (jint)addStateSetWithIntArray:(IOSIntArray *)stateSet
                 withADDrawable:(ADDrawable *)drawable;

- (jint)getCapacity;

- (jint)indexOfStateSetWithIntArray:(IOSIntArray *)stateSet;

@end

J2OBJC_EMPTY_STATIC_INIT(ADStateListDrawable)

FOUNDATION_EXPORT void ADStateListDrawable_init(ADStateListDrawable *self);

FOUNDATION_EXPORT ADStateListDrawable *new_ADStateListDrawable_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ADStateListDrawable *create_ADStateListDrawable_init(void);

FOUNDATION_EXPORT jboolean ADStateListDrawable_isWildCardWithIntArray_(IOSIntArray *stateSetOrSpec);

FOUNDATION_EXPORT jboolean ADStateListDrawable_stateSetMatchesWithIntArray_withIntArray_(IOSIntArray *stateSpec, IOSIntArray *stateSet);

J2OBJC_TYPE_LITERAL_HEADER(ADStateListDrawable)

@compatibility_alias RAndroidGraphicsDrawableStateListDrawable ADStateListDrawable;

#endif

#pragma pop_macro("INCLUDE_ALL_StateListDrawable")
