//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-javafx-widget\SWTAndroid\src\main\stub\r\android\annotation\SuppressLint.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "SuppressLint.h"


@implementation ADSuppressLint

@synthesize value = value_;

- (IOSClass *)annotationType {
  return ADSuppressLint_class_();
}

- (NSString *)description {
  return [NSString stringWithFormat:@"@r.android.annotation.SuppressLint(value=%@)", value_];
}

- (jboolean)isEqual:(id)obj {
  return JreAnnotationEquals(self, obj);
}

- (NSUInteger)hash {
  return JreAnnotationHashCode(self);
}

- (void)dealloc {
  RELEASE_(value_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(value);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "value_", "[LNSString;", .constantValue.asLong = 0, 0x1000, -1, -1, -1, -1 },
  };
  static const J2ObjcClassInfo _ADSuppressLint = { "SuppressLint", "r.android.annotation", NULL, methods, fields, 7, 0x2609, 1, 1, -1, -1, -1, -1, -1 };
  return &_ADSuppressLint;
}

@end

id<ADSuppressLint> create_ADSuppressLint(IOSObjectArray *value) {
  ADSuppressLint *self = AUTORELEASE([[ADSuppressLint alloc] init]);
  self->value_ = RETAIN_(value);
  return self;
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ADSuppressLint)
