//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-widget_library\css_parser\src\com\ashera\css\CssTree.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CssTree")
#ifdef RESTRICT_CssTree
#define INCLUDE_ALL_CssTree 0
#else
#define INCLUDE_ALL_CssTree 1
#endif
#undef RESTRICT_CssTree

#if !defined (CSSCssTree_) && (INCLUDE_ALL_CssTree || defined(INCLUDE_CSSCssTree))
#define CSSCssTree_

@protocol CSSCssResult;
@protocol JavaUtilList;

@interface CSSCssTree : NSObject

#pragma mark Public

- (instancetype)init;

- (void)end;

- (void)getCssWithNSString:(NSString *)tag
              withNSString:(NSString *)classNames
              withNSString:(NSString *)id_
          withCSSCssResult:(id<CSSCssResult>)cssResult;

- (id<JavaUtilList>)getFontFaces;

- (id<JavaUtilList>)getStyleWithNSString:(NSString *)selector;

- (void)setAttributeWithNSString:(NSString *)gaurdKeys
                    withNSString:(NSString *)gaurdValues
                    withNSString:(NSString *)attributeName
                    withNSString:(NSString *)key
                    withNSString:(NSString *)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CSSCssTree)

FOUNDATION_EXPORT void CSSCssTree_init(CSSCssTree *self);

FOUNDATION_EXPORT CSSCssTree *new_CSSCssTree_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CSSCssTree *create_CSSCssTree_init(void);

J2OBJC_TYPE_LITERAL_HEADER(CSSCssTree)

@compatibility_alias ComAsheraCssCssTree CSSCssTree;

#endif

#if !defined (CSSCssTree_Attribute_) && (INCLUDE_ALL_CssTree || defined(INCLUDE_CSSCssTree_Attribute))
#define CSSCssTree_Attribute_

@class CSSCssTree;

@interface CSSCssTree_Attribute : NSObject {
 @public
  NSString *key_;
  NSString *value_;
  NSString *orientation_;
  NSString *minWidth_;
  NSString *minHeight_;
  NSString *maxWidth_;
  NSString *maxHeight_;
}

#pragma mark Public

- (instancetype)initWithCSSCssTree:(CSSCssTree *)outer$
                      withNSString:(NSString *)key
                      withNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CSSCssTree_Attribute)

J2OBJC_FIELD_SETTER(CSSCssTree_Attribute, key_, NSString *)
J2OBJC_FIELD_SETTER(CSSCssTree_Attribute, value_, NSString *)
J2OBJC_FIELD_SETTER(CSSCssTree_Attribute, orientation_, NSString *)
J2OBJC_FIELD_SETTER(CSSCssTree_Attribute, minWidth_, NSString *)
J2OBJC_FIELD_SETTER(CSSCssTree_Attribute, minHeight_, NSString *)
J2OBJC_FIELD_SETTER(CSSCssTree_Attribute, maxWidth_, NSString *)
J2OBJC_FIELD_SETTER(CSSCssTree_Attribute, maxHeight_, NSString *)

FOUNDATION_EXPORT void CSSCssTree_Attribute_initWithCSSCssTree_withNSString_withNSString_(CSSCssTree_Attribute *self, CSSCssTree *outer$, NSString *key, NSString *value);

FOUNDATION_EXPORT CSSCssTree_Attribute *new_CSSCssTree_Attribute_initWithCSSCssTree_withNSString_withNSString_(CSSCssTree *outer$, NSString *key, NSString *value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CSSCssTree_Attribute *create_CSSCssTree_Attribute_initWithCSSCssTree_withNSString_withNSString_(CSSCssTree *outer$, NSString *key, NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(CSSCssTree_Attribute)

#endif

#pragma pop_macro("INCLUDE_ALL_CssTree")
